import './globals.css'
import {Providers} from './providers'

import type {Metadata} from 'next'

import {inter} from '@/components/layout'
import {StyledToastContainer} from '@/components/layout'
import {NavbarView} from '@/components/views/navbar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    robots: {index: false},
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <Providers>
                <body className={`${inter.className} flex min-h-screen w-full flex-col bg-layer-0 text-black antialiased dark:bg-layer-0-dark dark:text-white`}>
                    <NavbarView />
                    {children}
                    <StyledToastContainer />
                </body>
            </Providers>
        </html>
    )
}
